FROM node:20-alpine as base 

WORKDIR /app 

FROM base as development 

COPY package.json .
RUN npm install 

COPY . . 

EXPOSE 5000
CMD ["npx","nodemon", "index.js" ]


FROM base as production 

COPY package.json .
RUN npm install --only=production
COPY . . 
EXPOSE 5000
CMD ["node", "app.js"]